# Generated by Django 6.0.3 on 2026-03-30 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ID_number',
            field=models.CharField(max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='position',
            field=models.CharField(choices=[('OVERALL MANAGER', 'Overall Manager'), ('SITE MANAGER', 'Site Manager'), ('HOD', 'Head Of Department'), ('FOREMAN', 'Foreman'), ('ASSISTANT MANAGER', 'Assistant Manager'), ('ASSISTANT FOREMAN', 'Assistant Foreman'), ('STOREKEEPER', 'Storekeeper'), ('CASHIER', 'Cashier'), ('OTHERS', 'Others')], default='Others', max_length=50),
        ),
    ]
