# Generated by Django 6.0.3 on 2026-04-15 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_alter_position_payment_basis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='payment_basis',
            field=models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('MANUAL', 'Manual')], max_length=10),
        ),
    ]
