# Generated by Django 6.0.3 on 2026-04-04 07:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_alter_user_id_number_alter_user_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=50)),
                ('payment_basis', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly')], max_length=10)),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('assistant_forman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assistant_forman', to=settings.AUTH_USER_MODEL)),
                ('department', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='management.department')),
                ('forman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forman', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
