# Generated by Django 6.0.3 on 2026-04-04 07:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='assistant_forman',
        ),
        migrations.RemoveField(
            model_name='position',
            name='forman',
        ),
        migrations.AddField(
            model_name='position',
            name='assistant_foreman',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='assistant_foreman', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='position',
            name='foreman',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='foreman', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='position',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.department'),
        ),
    ]
