# Generated by Django 6.0.3 on 2026-05-10 15:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_alter_position_payment_basis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='date_employed',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
