# Generated by Django 6.0.3 on 2026-04-04 07:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_remove_position_assistant_forman_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='assistant_foreman',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='assistant_foreman', to=settings.AUTH_USER_MODEL),
        ),
    ]
