# Generated by Django 6.0.3 on 2026-05-10 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_alter_employee_date_employed'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='accumulated_salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
