# Generated by Django 6.0.3 on 2026-04-04 07:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_alter_position_assistant_foreman'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='foreman',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foreman', to=settings.AUTH_USER_MODEL),
        ),
    ]
