# Generated by Django 6.0.3 on 2026-04-04 09:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_alter_position_assistant_foreman'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='HOD',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
        migrations.AlterField(
            model_name='position',
            name='foreman',
            field=models.ForeignKey(limit_choices_to=models.Q(('position', 'FOREMAN'), ('position', 'HOD'), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, related_name='foreman', to=settings.AUTH_USER_MODEL),
        ),
    ]
