# Generated by Django 6.0.3 on 2026-04-04 10:08

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0008_alter_department_hod_alter_position_foreman'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(blank=True, default='blank_passport.webp', upload_to=''),
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=13)),
                ('passport', models.ImageField(blank=True, default='blank_passport.webp', upload_to='')),
                ('date_employed', models.DateTimeField(default=datetime.datetime.now)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.position')),
            ],
        ),
    ]
