# Generated by Django 6.0.3 on 2026-04-04 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyEmployeesActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unpaid_days', models.PositiveIntegerField(default=0)),
                ('hotel_bill', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('obligations', models.TextField(blank=True, max_length=1000, null=True)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyEmployeesActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unpaid_months', models.PositiveIntegerField(default=0)),
                ('hotel_bill', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('obligations', models.TextField(blank=True, max_length=1000, null=True)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='WeeklyEmployeesActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unpaid_weeks', models.PositiveIntegerField(default=0)),
                ('hotel_bill', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('obligations', models.TextField(blank=True, max_length=1000, null=True)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
