# Generated by Django 6.0.3 on 2026-04-04 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activity_log', '0001_initial'),
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyemployeesactivitylog',
            name='employee',
            field=models.ForeignKey(limit_choices_to=models.Q(('position__payment_basis', 'DAILY')), on_delete=django.db.models.deletion.CASCADE, to='management.employee'),
        ),
        migrations.AddField(
            model_name='monthlyemployeesactivitylog',
            name='employee',
            field=models.ForeignKey(limit_choices_to=models.Q(('position__payment_basis', 'MONTHLY')), on_delete=django.db.models.deletion.CASCADE, to='management.employee'),
        ),
        migrations.AddField(
            model_name='weeklyemployeesactivitylog',
            name='employee',
            field=models.ForeignKey(limit_choices_to=models.Q(('position__payment_basis', 'WEEKLY')), on_delete=django.db.models.deletion.CASCADE, to='management.employee'),
        ),
    ]
