# Generated by Django 6.0.3 on 2026-04-05 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity_log', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailyemployeesactivitylog',
            old_name='unpaid_days',
            new_name='unpaid_period',
        ),
        migrations.RenameField(
            model_name='monthlyemployeesactivitylog',
            old_name='unpaid_months',
            new_name='unpaid_period',
        ),
        migrations.RenameField(
            model_name='weeklyemployeesactivitylog',
            old_name='unpaid_weeks',
            new_name='unpaid_period',
        ),
    ]
