# Generated by Django 6.0.3 on 2026-04-05 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_log', '0003_rename_unpaid_days_dailyemployeesactivitylog_unpaid_period_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyemployeesactivitylog',
            name='present_today',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='dailyemployeesactivitylog',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='monthlyemployeesactivitylog',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='weeklyemployeesactivitylog',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
