# Generated by Django 6.0.3 on 2026-04-05 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity_log', '0004_dailyemployeesactivitylog_present_today_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyemployeesactivitylog',
            name='balance',
        ),
    ]
