# Generated by Django 6.0.3 on 2026-04-05 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_log', '0005_remove_dailyemployeesactivitylog_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyemployeesactivitylog',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
        ),
    ]
