# Generated by Django 6.0.3 on 2026-04-05 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_log', '0006_dailyemployeesactivitylog_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyemployeesactivitylog',
            name='balance',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10),
        ),
    ]
