# Generated by Django 6.0.3 on 2026-04-05 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_log', '0008_alter_dailyemployeesactivitylog_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlyemployeesactivitylog',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='weeklyemployeesactivitylog',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
        ),
    ]
