# Generated by Django 6.0.3 on 2026-04-05 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_log', '0009_alter_monthlyemployeesactivitylog_balance_and_more'),
        ('management', '0002_alter_position_payment_basis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyemployeesactivitylog',
            name='employee',
            field=models.ForeignKey(limit_choices_to=models.Q(('position__payment_basis', 'DAILY')), on_delete=django.db.models.deletion.CASCADE, to='management.employee', unique_for_date=True),
        ),
        migrations.AlterField(
            model_name='monthlyemployeesactivitylog',
            name='employee',
            field=models.ForeignKey(limit_choices_to=models.Q(('position__payment_basis', 'MONTHLY')), on_delete=django.db.models.deletion.CASCADE, to='management.employee', unique_for_month=True),
        ),
    ]
