# Generated by Django 6.0.3 on 2026-04-16 04:57

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_log', '0012_dailyemployeesactivitylog_date_and_more'),
        ('management', '0003_alter_position_payment_basis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monthlyemployeesactivitylog',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='weeklyemployeesactivitylog',
            name='employee',
        ),
        migrations.CreateModel(
            name='DailyActivitie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(default=datetime.datetime.now)),
                ('obligation', models.TextField()),
                ('hotel_bill', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('present', models.BooleanField(default=False)),
                ('attendance_fraction', models.CharField(default=1, max_length=10)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.employee')),
            ],
        ),
        migrations.DeleteModel(
            name='DailyEmployeesActivityLog',
        ),
        migrations.DeleteModel(
            name='MonthlyEmployeesActivityLog',
        ),
        migrations.DeleteModel(
            name='WeeklyEmployeesActivityLog',
        ),
    ]
