# Generated by Django 6.0.3 on 2026-04-17 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_log', '0013_remove_monthlyemployeesactivitylog_employee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyactivitie',
            name='attendance_fraction',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
