# Generated by Django 6.0.3 on 2026-04-17 04:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_log', '0014_alter_dailyactivitie_attendance_fraction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyactivitie',
            name='day',
            field=models.DateField(default=datetime.datetime.now, editable=False),
        ),
    ]
