# Generated by Django 6.0.3 on 2026-04-17 04:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_log', '0017_alter_dailyactivitie_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyactivitie',
            name='day',
            field=models.DateField(default=datetime.date(2026, 4, 17), editable=False),
        ),
    ]
