# Generated by Django 6.0.3 on 2026-04-17 04:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_log', '0018_alter_dailyactivitie_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyactivitie',
            name='day',
            field=models.DateField(default=django.utils.timezone.now, editable=False),
        ),
    ]
