# Generated by Django 6.0.3 on 2026-04-17 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_log', '0019_alter_dailyactivitie_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyactivitie',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='dailyactivitie',
            name='obligation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
