# Generated by Django 6.0.3 on 2026-04-17 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_log', '0020_alter_dailyactivitie_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyactivitie',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
        ),
    ]
