# Generated by Django 6.0.3 on 2026-05-10 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_log', '0022_alter_dailyactivitie_day'),
        ('management', '0004_alter_employee_date_employed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyactivitie',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.employee', unique_for_date='day'),
        ),
        migrations.AlterField(
            model_name='dailyactivitie',
            name='hotel_bill',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
    ]
