# Generated by Django 6.0.3 on 2026-05-10 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_log', '0023_alter_dailyactivitie_employee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyactivitie',
            name='posted',
            field=models.BooleanField(default=False),
        ),
    ]
